# coding: utf-8

"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bitdotio
from bitdotio.models.repo_collaborators import RepoCollaborators  # noqa: E501
from bitdotio.rest import ApiException

class TestRepoCollaborators(unittest.TestCase):
    """RepoCollaborators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RepoCollaborators
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bitdotio.models.repo_collaborators.RepoCollaborators()  # noqa: E501
        if include_optional :
            return RepoCollaborators(
                role = '0', 
                role_display = '0', 
                user = '0'
            )
        else :
            return RepoCollaborators(
                role = '0',
        )

    def testRepoCollaborators(self):
        """Test RepoCollaborators"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
