# coding: utf-8

"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bitdotio
from bitdotio.models.q_connection import QConnection  # noqa: E501
from bitdotio.rest import ApiException

class TestQConnection(unittest.TestCase):
    """QConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test QConnection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bitdotio.models.q_connection.QConnection()  # noqa: E501
        if include_optional :
            return QConnection(
                url = '0', 
                name = '0', 
                owner = '0', 
                kind = 'REST_CONNECTION'
            )
        else :
            return QConnection(
        )

    def testQConnection(self):
        """Test QConnection"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
