# coding: utf-8

"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import bitdotio
from bitdotio.models.table import Table  # noqa: E501
from bitdotio.rest import ApiException

class TestTable(unittest.TestCase):
    """Table unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Table
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = bitdotio.models.table.Table()  # noqa: E501
        if include_optional :
            return Table(
                url = '0', 
                current_name = '0', 
                description = '0', 
                columns = [
                    '0'
                    ], 
                num_records = 56, 
                bytes = '0', 
                repo = '0', 
                documentation = '0'
            )
        else :
            return Table(
        )

    def testTable(self):
        """Test Table"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
