"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bitdotio
from bitdotio.model.import_json import ImportJson


class TestImportJson(unittest.TestCase):
    """ImportJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testImportJson(self):
        """Test ImportJson"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ImportJson()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
