"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


import unittest

import bitdotio
from bitdotio.api.api_bitdotio import ApiBitdotio  # noqa: E501


class TestApiBitdotio(unittest.TestCase):
    """ApiBitdotio unit test stubs"""

    def setUp(self):
        self.api = ApiBitdotio()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_import_file(self):
        """Test case for create_import_file

        """
        pass

    def test_create_import_json(self):
        """Test case for create_import_json

        """
        pass

    def test_create_import_url(self):
        """Test case for create_import_url

        """
        pass

    def test_create_query(self):
        """Test case for create_query

        """
        pass

    def test_create_repo(self):
        """Test case for create_repo

        """
        pass

    def test_destroy_repo(self):
        """Test case for destroy_repo

        """
        pass

    def test_list_repos(self):
        """Test case for list_repos

        """
        pass

    def test_partial_update_repo(self):
        """Test case for partial_update_repo

        """
        pass

    def test_retrieve_ingestor_job(self):
        """Test case for retrieve_ingestor_job

        """
        pass

    def test_retrieve_repo(self):
        """Test case for retrieve_repo

        """
        pass

    def test_update_repo(self):
        """Test case for update_repo

        """
        pass


if __name__ == '__main__':
    unittest.main()
