"""
    bit.io REST API

    bit.io API  # noqa: E501

    The version of the OpenAPI document: 1.0.0b
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import bitdotio
from bitdotio.model.query import Query


class TestQuery(unittest.TestCase):
    """Query unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuery(self):
        """Test Query"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Query()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
